export const CONTACT_FORM_VALUES = "CONTACT_FORM_VALUES";
export const CONTACT_FORM_SUBMIT = "CONTACT_FORM_SUBMIT";
export const CONTACT_FORM_SUBMIT_SUCCESS = "CONTACT_FORM_SUBMIT_SUCCESS";
export const CONTACT_FORM_SUBMIT_FAILURE = "CONTACT_FORM_SUBMIT_FAILURE";
export const CONTACT_FORM_RESET = "CONTACT_FORM_RESET";
