const LABEL_HOME_GREETING = "G'day, I'm Kiran";
const LABEL_JOB_ROLE = 'Software Engineer';
const LABEL_CONTACT = 'Contact';
const LABEL_FIRST_NAME = 'First Name';
const LABEL_SECOND_NAME = 'Second Name';
const LABLE_PHONE = "Phone";
const LABEL_EMAIL = "Email";
const LABEL_MESSAGE = 'Message';
const LABEL_SUBMIT = "SUBMIT";
const LABEL_ABOUT = "About";
const LABEL_SKILLS = "Skills";
const LABLE_EXPERIENCE = 'Experience';
const LABEL_EDUCATION = 'Education';
const LABEL_DOWNLOAD_RESUME = 'Download Resume';

export {
	LABEL_HOME_GREETING,
	LABEL_JOB_ROLE,
	LABEL_CONTACT,
	LABEL_FIRST_NAME,
	LABEL_SECOND_NAME,
	LABLE_PHONE,
	LABEL_EMAIL,
	LABEL_MESSAGE,
	LABEL_SUBMIT,
	LABEL_ABOUT,
	LABEL_SKILLS,
	LABLE_EXPERIENCE,
	LABEL_EDUCATION,
	LABEL_DOWNLOAD_RESUME
};
